id: AD7B0150A
title: Prayer to the Siddha Virūpa
type: translation
pechas:
- I1CF8C9D3
- IA32E2EB2
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:35:57.365490
  last_modified_at: 2023-01-04 12:35:57.365497
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I1CF8C9D3/A161: B52A
  IA32E2EB2/93B0: B52A
